export const Projects = [
    {
        id:1,
        state: 1,
        favorite: true,
        date: "03/04/21",
        users: 18,
        name: "Nombre del proyecto",
        address: "Dirección del proyecto",
        amount: "2.000.030 USD",
        mesures: "960m2",
        photo: "",
        ppc: "15%",
        pcr: "46%",
        completed: "81%",
    },
    {
        id:1,
        state: 2,
        favorite: true,
        date: "03/04/21",
        users: 18,
        name: "Nombre del proyecto",
        address: "Dirección del proyecto",
        amount: "2.000.030 USD",
        mesures: "960m2",
        photo: "",
        ppc: "15%",
        pcr: "46%",
        completed: "81%",
    },
    {
        id:1,
        state: 3,
        favorite: true,
        date: "03/04/21",
        users: 18,
        name: "Nombre del proyecto",
        address: "Dirección del proyecto",
        amount: "2.000.030 USD",
        mesures: "960m2",
        photo: "",
        ppc: "15%",
        pcr: "46%",
        completed: "81%",
    },
    {
        id:1,
        state: 4,
        favorite: false,
        date: "03/04/21",
        users: 18,
        name: "Nombre del proyecto",
        address: "Dirección del proyecto",
        amount: "2.000.030 USD",
        mesures: "960m2",
        photo: "",
        ppc: "15%",
        pcr: "46%",
        completed: "81%",
    },
    {
        id:1,
        state: 1,
        favorite: false,
        date: "03/04/21",
        users: 18,
        name: "Nombre del proyecto",
        address: "Dirección del proyecto",
        amount: "2.000.030 USD",
        mesures: "960m2",
        photo: "",
        ppc: "15%",
        pcr: "46%",
        completed: "81%",
    },
    {
        id:1,
        state: 1,
        favorite: false,
        date: "03/04/21",
        users: 18,
        name: "Nombre del proyecto",
        address: "Dirección del proyecto",
        amount: "2.000.030 USD",
        mesures: "960m2",
        photo: "",
        ppc: "15%",
        pcr: "46%",
        completed: "81%",
    },
    {
        id:1,
        state: 1,
        favorite: false,
        date: "03/04/21",
        users: 18,
        name: "Nombre del proyecto",
        address: "Dirección del proyecto",
        amount: "2.000.030 USD",
        mesures: "960m2",
        photo: "",
        ppc: "15%",
        pcr: "46%",
        completed: "81%",
    },
    {
        id:1,
        state: 2,
        favorite: false,
        date: "03/04/21",
        users: 18,
        name: "Nombre del proyecto",
        address: "Dirección del proyecto",
        amount: "2.000.030 USD",
        mesures: "960m2",
        photo: "",
        ppc: "15%",
        pcr: "46%",
        completed: "81%",
    },
    {
        id:1,
        state: 2,
        favorite: false,
        date: "03/04/21",
        users: 18,
        name: "Nombre del proyecto",
        address: "Dirección del proyecto",
        amount: "2.000.030 USD",
        mesures: "960m2",
        photo: "",
        ppc: "15%",
        pcr: "46%",
        completed: "81%",
    },
    {
        id:1,
        state: 3,
        favorite: false,
        date: "03/04/21",
        users: 18,
        name: "Nombre del proyecto",
        address: "Dirección del proyecto",
        amount: "2.000.030 USD",
        mesures: "960m2",
        photo: "",
        ppc: "15%",
        pcr: "46%",
        completed: "81%",
    },
    {
        id:1,
        state: 4,
        favorite: false,
        date: "03/04/21",
        users: 18,
        name: "Nombre del proyecto",
        address: "Dirección del proyecto",
        amount: "2.000.030 USD",
        mesures: "960m2",
        photo: "",
        ppc: "15%",
        pcr: "46%",
        completed: "81%",
    },
    {
        id:1,
        state: 4,
        favorite: false,
        date: "03/04/21",
        users: 18,
        name: "Nombre del proyecto",
        address: "Dirección del proyecto",
        amount: "2.000.030 USD",
        mesures: "960m2",
        photo: "",
        ppc: "15%",
        pcr: "46%",
        completed: "81%",
    },

]